In [19]:
import numpy as np

In [49]:
fn = 'day1.txt'
D = open(fn).read().strip()

store_max = 0
store = 0
store_max_arr = np.array([0,0,0])
for line in D.split('\n'):
    # print("="*8)
    # print(line)
    # print(store)
    # print(store_max_arr)
    # if(store > 63967):
    #     print("HEY")
    #     print(store)
    #     break
    if line == '':
        if store > store_max:
            store_max = store
        for i, val in enumerate(store_max_arr):
            if store > val:
                print("="*10)
                print(store)
                print(i, val)
                if i == 0:
                    store_max_arr[2] = store_max_arr[1] 
                    store_max_arr[1] = store_max_arr[0] 
                elif i == 1: 
                    store_max_arr[2] = store_max_arr[1] 
                store_max_arr[i] = store 
                print(store_max_arr)
                store = 0
                break
            
        store = 0
    else:
        store += int(line)

# if store > store_max:
#     store_max = store

print(store_max)
print(store_max_arr)
print(np.sum(store_max_arr))

47448
0 0
[47448     0     0]
45090
1 0
[47448 45090     0]
59018
0 47448
[59018 47448 45090]
49618
1 47448
[59018 49618 47448]
63645
0 59018
[63645 59018 49618]
58355
2 49618
[63645 59018 58355]
63322
1 59018
[63645 63322 59018]
59112
2 59018
[63645 63322 59112]
61732
2 59112
[63645 63322 61732]
63592
1 63322
[63645 63592 63322]
63967
0 63645
[63967 63645 63592]
67023
0 63967
[67023 63967 63645]
64098
1 63967
[67023 64098 63967]
68923
0 67023
[68923 67023 64098]
68923
[68923 67023 64098]
200044


In [45]:
print(np.roll(store_max_arr, 0))
print(np.roll(store_max_arr[0:2], 1))
np.roll(store_max_arr, 2)

[68923 64098 63509]
[64098 68923]


array([64098, 63509, 68923])